apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ahamedkhany/my-argo-demo.git
    targetRevision: main
    path: helm-chart/
    helm:
      valueFiles:
      - values-prod.yaml  # Use production values
      #parameters:
      #- name: replicaCount
      #  value: "3"        # Override replicas to 3

  destination:
    server: https://kubernetes.default.svc
    namespace: helm-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true